# Generated by Django 6.0.2 on 2026-02-28 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("narration", models.TextField()),
                ("reference", models.CharField(max_length=100)),
                ("transaction_date", models.DateTimeField()),
                ("matched", models.BooleanField(default=False)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="accounts.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReconciliationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("auto_matched", "Auto Matched"),
                            ("manual_review", "Manual Review"),
                            ("unmatched", "Unmatched"),
                        ],
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_logs",
                        to="reconciliation.banktransaction",
                    ),
                ),
                (
                    "matched_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_logs",
                        to="students.student",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_logs",
                        to="accounts.school",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["reference"], name="reconciliat_referen_90ef59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["transaction_date"], name="reconciliat_transac_e125e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("school", "reference"), name="unique_school_bank_reference"
            ),
        ),
    ]
